# Generated by Django 4.1 on 2023-03-20 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_cetatean_options_cetatean_mail_cetatean_nume_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatHandicap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad_handicap', models.CharField(choices=[('Usor', 'Usor'), ('Mediu', 'Mediu'), ('Accentuat', 'Accentuat'), ('Grav cu asistent personal', 'Grav Cu Asistent Personal'), ('Grav', 'Grav')], max_length=50)),
                ('tip_handicap', models.CharField(choices=[('Fizic', 'Fizic'), ('Vizual', 'Vizual'), ('Auditiv', 'Auditiv'), ('Surdocecitate', 'Surdocecitate'), ('Somatic', 'Somatic'), ('Mintal', 'Mintal'), ('Psihic', 'Psihic'), ('HIV/SIDA', 'Hiv Sida'), ('Asociat', 'Asociat'), ('Boli rare', 'Boli Rare')], max_length=50)),
                ('cetatean', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authentication.cetatean')),
            ],
            options={
                'verbose_name': 'Certificat Handicap',
                'verbose_name_plural': 'Certificate Handicap',
            },
        ),
    ]
