# Generated by Django 4.1 on 2023-03-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificathandicap'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificathandicap',
            name='link_descarcare_document',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
