# Generated by Django 4.1 on 2023-03-22 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_cetatean_options_cetatean_mail_cetatean_nume_and_more'),
        ('main', '0003_certificathandicap_link_descarcare_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatInregistrarePFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_firma', models.CharField(max_length=100)),
                ('cod_CAEN', models.CharField(max_length=20)),
                ('sediu_profesional', models.CharField(max_length=100)),
                ('CUI', models.CharField(max_length=20)),
                ('EUID', models.CharField(max_length=20)),
                ('numar_de_ordine_ONRC', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=20)),
                ('numar', models.CharField(max_length=20)),
                ('data_eliberare', models.DateField()),
                ('cetatean', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authentication.cetatean')),
            ],
            options={
                'verbose_name': 'Certificat Inregistrare PFA',
                'verbose_name_plural': 'Certificate Inregistrare PFA',
            },
        ),
    ]
