# Generated by Django 4.1 on 2023-03-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_certificatinregistrarepfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatinregistrarepfa',
            name='link_descarcare_document',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
