# Generated by Django 4.1 on 2023-03-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cetatean',
            options={'verbose_name': 'Cetatean', 'verbose_name_plural': 'Cetateni'},
        ),
        migrations.AddField(
            model_name='cetatean',
            name='mail',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cetatean',
            name='nume',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cetatean',
            name='prenume',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
